language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  # Composer
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
  - composer self-update
  - composer update --prefer-source
script:
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration tests/phpunit.xml.dist --coverage-text
  - mkdir .reports
  # Code style
  - php vendor/bin/phpcs ./src/Bluz --standard=PSR1 --report=summary
  - php vendor/bin/phpcs ./src/Bluz --standard=PSR2 --report=summary
  # Duplicate code
  - php vendor/bin/phpcpd --log-pmd .reports/pmd-cpd.xml src/Bluz
notifications:
  email: github@nixsolutions.com
